# Generated by Django 2.2.7 on 2020-02-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
